# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SimonSaysLab' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimonSaysLab

  target 'SimonSaysLabTests' do
    inherit! :search_paths
    # Pods for testing

	pod 'Quick', '~> 0.9'
	pod 'Nimble', '~> 4.0'

  end

end
